ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#928374'

typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#ea6962'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#d3869b'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[function]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#a9b665'
ZSH_HIGHLIGHT_STYLES[path]='fg=#7daea3'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#7daea3'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#d3869b'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#d8a657'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#d8a657'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#d8a657'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#d8a657'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#7daea3'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#928374'
