start-at-login = true
after-login-command = []
after-startup-command = [ 
  # 'exec-and-forget sketchybar',
]

key-mapping.preset = 'qwerty'

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 12

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# exec-on-workspace-change = [
#   '/bin/bash', 
#   '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
# ]

# exec-on-workspace-change = ['/Users/bruno/.config/aerospace/on-ws-change.sh']

on-focus-changed = [
  # 'exec-and-forget sketchybar --trigger front_app_switched'
  # 'exec-and-forget sketchybar --trigger send_message MESSAGE="Focus has changed"'
]

[gaps]
outer.top =        [{ monitor."built-in.*" = 4 }, -8]
outer.left =       12
outer.bottom =     12
outer.right =      12
inner.horizontal = 12
inner.vertical =   12

[workspace-to-monitor-force-assignment]
Browser = [ 'secondary', 'main' ]
Simulator = [ 'secondary', 'main' ]

[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-semicolon = [
  'mode service',
  # 'exec-and-forget sketchybar --trigger send_message MESSAGE="Aerospace in Service Mode" HOLD="true"',
]

alt-tab = 'workspace-back-and-forth'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-b = 'workspace Browser'
alt-c = 'workspace Coding'
alt-e = 'workspace Email'
alt-f = 'workspace Files'
alt-s = 'workspace Simulator'
alt-t = 'workspace Terminal'
alt-x = 'workspace X'

alt-shift-b = 'move-node-to-workspace Browser'
alt-shift-c = 'move-node-to-workspace Coding'
alt-shift-e = 'move-node-to-workspace Email'
alt-shift-f = 'move-node-to-workspace Files'
alt-shift-s = 'move-node-to-workspace Simulator'
alt-shift-t = 'move-node-to-workspace Terminal'
alt-shift-x = 'move-node-to-workspace X'

# alt-m = 'exec-and-forget sketchybar --trigger aerospace_switch'

[mode.service.binding]
esc = [
  'reload-config', 
  'mode main', 
  # 'exec-and-forget sketchybar --reload',
  # 'exec-and-forget sleep 0.2 && sketchybar --trigger send_message MESSAGE="Aerospace Reloaded"',
]

t = [
  'layout h_tiles v_accordion', 
] 
f = [
  'layout floating tiling', 
] 
# backspace = ['close-all-windows-but-current', 'mode main']

minus = 'resize smart -50'
equal = 'resize smart +50'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace Terminal']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
check-further-callbacks = true
run = ['move-node-to-workspace Browser']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
check-further-callbacks = true
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
check-further-callbacks = true
run = ['move-node-to-workspace Browser']

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
check-further-callbacks = true
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace Coding'] 

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace Files']

[[on-window-detected]]
if.app-id = 'org.mozilla.thunderbirdbeta'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace Email']

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace Simulator']

