version = 3
final_space = false

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "session"
style = "plain"
foreground_templates = [
  "{{ if .SSHSession }}#7DAEA3{{ end }}",
  "{{ if not .SSHSession }}#89B482{{ end }}",
]
template = "{{ .HostName }}{{ if .SSHSession }} [ssh]{{ end }}"

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "#D8A657"
template = " {{ .Path }}"

[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "#E78A4E"
template = " [{{ .HEAD }}]"

[blocks.segments.properties]
branch_icon = ""
fetch_status = false

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "#D3869B"
template = "{{ if .Env.DIRENV_DIR }} [dev]{{ end }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "#D4BE98"
template = "$ "
